using ChessV1;

namespace PreInitializeDataV1
{
    public class CharToPiece
    {
        public static byte GetPiece(char c) => data[c - 'A'];
        private static readonly byte[] data =
        {
            (byte)0, // 'A'
            (byte)Piece.WBishop, // 'B'
            (byte)0, // 'C'
            (byte)0, // 'D'
            (byte)0, // 'E'
            (byte)0, // 'F'
            (byte)0, // 'G'
            (byte)0, // 'H'
            (byte)0, // 'I'
            (byte)0, // 'J'
            (byte)Piece.WKing, // 'K'
            (byte)0, // 'L'
            (byte)0, // 'M'
            (byte)Piece.WKnight, // 'N'
            (byte)0, // 'O'
            (byte)Piece.WPawn, // 'P'
            (byte)Piece.WQueen, // 'Q'
            (byte)Piece.WRook, // 'R'
            (byte)0, // 'S'
            (byte)0, // 'T'
            (byte)0, // 'U'
            (byte)0, // 'V'
            (byte)0, // 'W'
            (byte)0, // 'X'
            (byte)0, // 'Y'
            (byte)0, // 'Z'
            (byte)0, // '['
            (byte)0, // '\'
            (byte)0, // ']'
            (byte)0, // '^'
            (byte)0, // '_'
            (byte)0, // '`'
            (byte)0, // 'a'
            (byte)Piece.BBishop, // 'b'
            (byte)0, // 'c'
            (byte)0, // 'd'
            (byte)0, // 'e'
            (byte)0, // 'f'
            (byte)0, // 'g'
            (byte)0, // 'h'
            (byte)0, // 'i'
            (byte)0, // 'j'
            (byte)Piece.BKing, // 'k'
            (byte)0, // 'l'
            (byte)0, // 'm'
            (byte)Piece.BKnight, // 'n'
            (byte)0, // 'o'
            (byte)Piece.BPawn, // 'p'
            (byte)Piece.BQueen, // 'q'
            (byte)Piece.BRook, // 'r'
            (byte)0, // 's'
            (byte)0, // 't'
            (byte)0, // 'u'
            (byte)0, // 'v'
            (byte)0, // 'w'
            (byte)0, // 'x'
            (byte)0, // 'y'
            (byte)0  // 'z'
        };
    }
}